// <auto-generated />
using FoodPandaClone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodPandaClone.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodPandaClone.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "JDS Coffee"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fresh Juice"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cookies"
                        });
                });

            modelBuilder.Entity("FoodPandaClone.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Strong and Bold Coffee",
                            ImageUrl = "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=400",
                            Name = "JDS Espresso",
                            Price = 180m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Sweet Caramel Bliss",
                            ImageUrl = "https://images.unsplash.com/photo-1485808191679-5f86510681a2?w=400",
                            Name = "Caramel Latte",
                            Price = 250m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Freshly Brewed Ice Coffee",
                            ImageUrl = "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400",
                            Name = "Iced Americano",
                            Price = 200m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Organic Fresh Mango",
                            ImageUrl = "https://images.unsplash.com/photo-1546173159-315724a31696?w=400",
                            Name = "Mango Blast",
                            Price = 120m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Natural Watermelon Squeeze",
                            ImageUrl = "https://images.unsplash.com/photo-1543158181-e6f9f697ce4b?w=400",
                            Name = "Watermelon Cooler",
                            Price = 100m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "High Vitamin C Orange",
                            ImageUrl = "https://images.unsplash.com/photo-1624517452488-04869289c4ca?w=400",
                            Name = "Orange Squeeze",
                            Price = 150m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Extra Chocolate Chips",
                            ImageUrl = "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=400",
                            Name = "Choco Chip Cookie",
                            Price = 60m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Crunchy Almonds Butter",
                            ImageUrl = "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=400",
                            Name = "Almond Crunch",
                            Price = 80m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Healthy Soft Oats",
                            ImageUrl = "https://images.unsplash.com/photo-1590080875515-8a03b1447d1a?w=400",
                            Name = "Oatmeal Raisin",
                            Price = 55m
                        });
                });

            modelBuilder.Entity("FoodPandaClone.Models.Product", b =>
                {
                    b.HasOne("FoodPandaClone.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodPandaClone.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
